import {
    Shield,
    Award,
    Star,
    Trophy,
    Flame,
    Heart,
    CheckCircle,
    Smile,
    BookOpen,
    Globe,
    Rocket,
    Target,
    Medal,
    ThumbsUp,
    Sun,
    Moon,
    Feather,
    Gift,
    Zap,
    Leaf,
} from "lucide-react-native";

export const BADGES = [
    {
        id: 1,
        name: "First Conversation",
        desc: "Complete your first chat",
        icon: Shield,
        unlocked: true,
    },
    {
        id: 2,
        name: "Streak Starter",
        desc: "Practice 3 days in a row",
        icon: Flame,
        unlocked: true,
    },
    {
        id: 3,
        name: "Quiz Master",
        desc: "Score 90+ in a session",
        icon: Award,
        unlocked: false,
    },
    {
        id: 4,
        name: "Polyglot",
        desc: "Try 3 different modes",
        icon: Globe,
        unlocked: false,
    },
    {
        id: 5,
        name: "Night Owl",
        desc: "Practice after midnight",
        icon: Moon,
        unlocked: false,
    },
    {
        id: 6,
        name: "Early Bird",
        desc: "Practice before 7am",
        icon: Sun,
        unlocked: false,
    },
    {
        id: 7,
        name: "Consistent",
        desc: "7-day streak",
        icon: CheckCircle,
        unlocked: false,
    },
    {
        id: 8,
        name: "Enthusiast",
        desc: "Complete 20 sessions",
        icon: Star,
        unlocked: false,
    },
    {
        id: 9,
        name: "Bookworm",
        desc: "Read 10 lesson tips",
        icon: BookOpen,
        unlocked: false,
    },
    {
        id: 10,
        name: "Motivator",
        desc: "Send 5 feedbacks",
        icon: Heart,
        unlocked: false,
    },
    {
        id: 11,
        name: "Champion",
        desc: "Score 100 in a session",
        icon: Trophy,
        unlocked: false,
    },
    {
        id: 12,
        name: "Rocket",
        desc: "Improve score by 20+",
        icon: Rocket,
        unlocked: false,
    },
    {
        id: 13,
        name: "Target Achiever",
        desc: "Hit your weekly goal",
        icon: Target,
        unlocked: false,
    },
    {
        id: 14,
        name: "Medalist",
        desc: "Unlock 10 badges",
        icon: Medal,
        unlocked: false,
    },
    {
        id: 15,
        name: "Positive Vibes",
        desc: "Give 10 thumbs up",
        icon: ThumbsUp,
        unlocked: false,
    },
    {
        id: 16,
        name: "Feather Touch",
        desc: "Use voice input",
        icon: Feather,
        unlocked: false,
    },
    {
        id: 17,
        name: "Gifted",
        desc: "Refer a friend",
        icon: Gift,
        unlocked: false,
    },
    {
        id: 18,
        name: "Lightning Fast",
        desc: "Finish a session in under 2 min",
        icon: Zap,
        unlocked: false,
    },
    {
        id: 19,
        name: "Green Leaf",
        desc: "Practice every day for a month",
        icon: Leaf,
        unlocked: false,
    },
    {
        id: 20,
        name: "Smiley",
        desc: "React to 10 messages",
        icon: Smile,
        unlocked: false,
    },
];
