import { StyleSheet } from "react-native";
import { useTheme } from "../../hooks/useTheme";

export const useLoginStyles = () => {
    const { colors } = useTheme();
    return StyleSheet.create({
        headerGradient: {
            backgroundColor: colors.primary,
            borderBottomLeftRadius: 48,
            borderBottomRightRadius: 48,
            padding: 32,
            paddingBottom: 48,
        },
        headerIcon: {
            width: 80,
            height: 80,
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        headerTitle: {
            color: colors.background,
            fontSize: 32,
            fontWeight: "bold",
            marginBottom: 8,
            textAlign: "center",
        },
        headerSubtitle: {
            color: "rgba(255,255,255,0.9)",
            fontSize: 16,
            textAlign: "center",
        },
        formSection: {
            flex: 1,
            paddingHorizontal: 20,
            marginTop: -30,
            paddingBottom: 32,
        },
        formContainer: {
            backgroundColor: colors.background,
            borderRadius: 24,
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
            padding: 20,
            marginBottom: 16,
        },
        signInTitle: {
            fontSize: 20,
            fontWeight: "bold",
            color: colors.textPrimary,
            marginBottom: 24,
        },
        // label: {
        //     fontSize: 14,
        //     fontWeight: "500",
        //     color: colors.textSecondary,
        //     marginBottom: 8,
        // },
        // inputWrapper: {
        //     flexDirection: "row",
        //     alignItems: "center",
        //     backgroundColor: colors.inputBackground,
        //     borderRadius: 16,
        //     borderWidth: 1,
        //     borderColor: colors.border,
        //     paddingHorizontal: 12,
        //     paddingVertical: 4,
        //     position: "relative",
        // },
        inputIcon: {
            marginRight: 8,
            color: colors.textPrimary,
        },
        // input: {
        //     flex: 1,
        //     paddingVertical: 12,
        //     fontSize: 16,
        //     color: colors.textPrimary,
        // },
        // eyeButton: {
        //     position: "absolute",
        //     right: 12,
        //     top: "50%",
        //     marginTop: -10,
        //     padding: 4,
        // },
        forgotPassword: {
            fontSize: 14,
            color: colors.secondary,
            fontWeight: "500",
        },
        signInButton: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            alignItems: "center",
            marginBottom: 16,
            shadowColor: colors.primary,
            shadowOpacity: 0.2,
            shadowRadius: 8,
            shadowOffset: { width: 0, height: 4 },
            elevation: 2,
        },
        signInButtonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        dividerContainer: {
            flexDirection: "row",
            alignItems: "center",
            marginVertical: 16,
        },
        dividerLine: {
            flex: 1,
            height: 1,
            backgroundColor: colors.border,
        },
        dividerText: {
            marginHorizontal: 12,
            color: colors.textSecondary,
            fontSize: 14,
            backgroundColor: colors.background,
            paddingHorizontal: 8,
        },
        socialRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: 24,
        },
        socialButton: {
            flex: 1,
            alignItems: "center",
            paddingVertical: 12,
            backgroundColor: colors.background,
            borderWidth: 2,
            borderColor: colors.border,
            borderRadius: 12,
            marginHorizontal: 4,
        },
        socialButtonText: {
            fontSize: 14,
            fontWeight: "500",
            color: colors.textPrimary,
        },
        signupText: {
            color: colors.secondary,
            fontSize: 14,
        },
        signupLink: {
            color: colors.primary,
            fontWeight: "600",
        },
        featuresRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginTop: 24,
            marginBottom: 10,
        },
        // featureItem: {
        //     alignItems: "center",
        //     flex: 1,
        // },
        // featureIcon: {
        //     width: 48,
        //     height: 48,
        //     borderRadius: 12,
        //     alignItems: "center",
        //     justifyContent: "center",
        //     marginBottom: 8,
        // },
        // featureText: {
        //     fontSize: 12,
        //     color: colors.textSecondary,
        //     fontWeight: "500",
        //     textAlign: "center",
        // },
        signUpButton: { alignItems: "center" },
        signupRow: {
            flexDirection: "row",
            gap: 4,
            alignSelf: "center",
            marginBottom: 0,
            paddingBottom: 10,
        },
    });
};

export const useRegisterStyles = () => {
    const { colors } = useTheme();

    return StyleSheet.create({
        headerGradient: {
            backgroundColor: colors.primary,
            borderBottomLeftRadius: 48,
            borderBottomRightRadius: 48,
            padding: 32,
            paddingBottom: 48,
        },
        headerIcon: {
            width: 80,
            height: 80,
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        headerTitle: {
            color: colors.background,
            fontSize: 32,
            fontWeight: "bold",
            marginBottom: 8,
            textAlign: "center",
        },
        headerSubtitle: {
            color: "rgba(255,255,255,0.9)",
            fontSize: 16,
            textAlign: "center",
        },
        formSection: {
            flex: 1,
            paddingHorizontal: 20,
            marginTop: -30,
        },
        formContainer: {
            backgroundColor: colors.background,
            borderRadius: 24,
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
            padding: 20,
            marginBottom: 16,
        },
        signUpTitle: {
            fontSize: 20,
            fontWeight: "bold",
            color: colors.textPrimary,
            marginBottom: 24,
        },
        label: {
            fontSize: 14,
            fontWeight: "500",
            color: colors.textSecondary,
            marginBottom: 8,
        },
        inputWrapper: {
            flexDirection: "row",
            alignItems: "center",
            backgroundColor: colors.inputBackground,
            borderRadius: 16,
            borderWidth: 1,
            borderColor: colors.border,
            paddingHorizontal: 12,
            paddingVertical: 4,
            position: "relative",
        },
        inputIcon: {
            marginRight: 8,
            color: colors.textPrimary,
        },
        input: {
            flex: 1,
            paddingVertical: 12,
            fontSize: 16,
            color: colors.textPrimary,
        },
        eyeButton: {
            position: "absolute",
            right: 12,
            top: "50%",
            marginTop: -10,
            padding: 4,
        },
        passwordHint: {
            fontSize: 12,
            color: colors.textSecondary,
            marginTop: -20,
            marginBottom: 20,
            marginLeft: 2,
        },
        checkboxRow: {
            flexDirection: "row",
            alignItems: "flex-start",
            marginBottom: 24,
            gap: 8,
        },
        checkbox: {
            width: 20,
            height: 20,
            borderRadius: 4,
            borderWidth: 1,
            borderColor: colors.border,
            marginTop: 2,
            marginRight: 8,
            backgroundColor: colors.background,
        },
        termsText: {
            fontSize: 13,
            color: colors.textSecondary,
            flex: 1,
            flexWrap: "wrap",
            flexDirection: "row",
        },
        link: {
            color: colors.primary,
            fontWeight: "500",
        },
        signUpButton: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            alignItems: "center",
            marginBottom: 16,
            shadowColor: colors.primary,
            shadowOpacity: 0.2,
            shadowRadius: 8,
            shadowOffset: { width: 0, height: 4 },
            elevation: 2,
        },
        signUpButtonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        dividerContainer: {
            flexDirection: "row",
            alignItems: "center",
            marginVertical: 16,
        },
        dividerLine: {
            flex: 1,
            height: 1,
            backgroundColor: colors.border,
        },
        dividerText: {
            marginHorizontal: 12,
            color: colors.textSecondary,
            fontSize: 14,
            backgroundColor: colors.background,
            paddingHorizontal: 8,
        },
        socialRow: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: 24,
            gap: 8,
        },
        socialButton: {
            flex: 1,
            alignItems: "center",
            paddingVertical: 12,
            backgroundColor: colors.background,
            borderWidth: 2,
            borderColor: colors.border,
            borderRadius: 12,
            marginHorizontal: 4,
        },
        socialButtonText: {
            fontSize: 14,
            fontWeight: "500",
            color: colors.textPrimary,
        },
        signinText: {
            color: colors.textSecondary,
            fontSize: 14,
        },
        signinLink: {
            color: colors.secondary,
            fontWeight: "600",
        },
        passwordRow: {
            flexDirection: "column",
        },
        trustContainer: {
            backgroundColor: "#faf5ff",
            borderRadius: 16,
            padding: 20,
            marginTop: 16,
            marginBottom: 32,
        },
        // trustRow: {
        //     flexDirection: "row",
        //     alignItems: "center",
        //     justifyContent: "center",
        // },
        // trustItem: {
        //     alignItems: "center",
        //     flex: 1,
        // },
        // trustValue: {
        //     fontSize: 20,
        //     fontWeight: "bold",
        //     marginBottom: 2,
        // },
        // trustLabel: {
        //     fontSize: 12,
        //     color: colors.textSecondary,
        //     textAlign: "center",
        // },
        // trustDivider: {
        //     width: 1,
        //     height: 40,
        //     backgroundColor: colors.border,
        //     marginHorizontal: 8,
        // },
        account: {
            alignItems: "center",
            flexDirection: "row",
            gap: 2,
            alignSelf: "center",
        },
        signInButton: { alignItems: "center" },
    });
};

export const useWelcomeStyles = () => {
    const { colors } = useTheme();

    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.background,
            justifyContent: "center",
            alignItems: "center",
            padding: 32,
        },
        title: {
            fontSize: 32,
            fontWeight: "bold",
            color: colors.primary,
            marginBottom: 16,
            textAlign: "center",
        },
        subtitle: {
            fontSize: 18,
            color: colors.textSecondary,
            marginBottom: 32,
            textAlign: "center",
        },
        button: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            paddingHorizontal: 32,
            alignItems: "center",
            marginBottom: 12,
            width: "100%",
        },
        buttonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        outlineButton: {
            borderWidth: 2,
            borderColor: colors.primary,
            backgroundColor: colors.background,
        },
        outlineButtonText: {
            color: colors.primary,
        },
    });
};

export const useForgotPasswordStyles = () => {
    const { colors } = useTheme();
    return StyleSheet.create({
        headerGradient: {
            backgroundColor: colors.primary,
            borderBottomLeftRadius: 48,
            borderBottomRightRadius: 48,
            padding: 32,
            paddingBottom: 48,
        },
        headerIcon: {
            width: 80,
            height: 80,
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        headerTitle: {
            color: colors.background,
            fontSize: 32,
            fontWeight: "bold",
            marginBottom: 8,
            textAlign: "center",
        },
        headerSubtitle: {
            color: "rgba(255,255,255,0.9)",
            fontSize: 16,
            textAlign: "center",
        },
        formSection: {
            flex: 1,
            paddingHorizontal: 20,
            marginTop: -24,
            paddingBottom: 32,
        },
        formContainer: {
            backgroundColor: colors.background,
            borderRadius: 24,
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
            padding: 20,
            marginBottom: 16,
        },
        // label: {
        //     fontSize: 14,
        //     fontWeight: "500",
        //     color: colors.textSecondary,
        //     marginBottom: 8,
        // },
        // inputWrapper: {
        //     flexDirection: "row",
        //     alignItems: "center",
        //     backgroundColor: colors.inputBackground,
        //     borderRadius: 16,
        //     borderWidth: 1,
        //     borderColor: colors.border,
        //     paddingHorizontal: 12,
        //     paddingVertical: 4,
        //     position: "relative",
        //     marginBottom: 24,
        // },
        inputIcon: {
            marginRight: 8,
            color: colors.textPrimary,
        },
        // input: {
        //     flex: 1,
        //     paddingVertical: 12,
        //     fontSize: 16,
        //     color: colors.textPrimary,
        // },
        resetButton: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            alignItems: "center",
            marginBottom: 8,
        },
        resetButtonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        successText: {
            color: colors.primary,
            fontSize: 16,
            textAlign: "center",
            marginVertical: 24,
            fontWeight: "500",
        },
        backToLoginText: {
            color: colors.secondary,
            fontSize: 15,
            fontWeight: "500",
        },
        backToLoginBtn: { alignItems: "center", marginTop: 16 },
        title: {
            fontSize: 20,
            fontWeight: "bold",
            color: colors.textPrimary,
            marginBottom: 24,
        },
    });
};

export const useOtpStyles = () => {
    const { colors } = useTheme();
    return StyleSheet.create({
        headerGradient: {
            backgroundColor: colors.primary,
            borderBottomLeftRadius: 48,
            borderBottomRightRadius: 48,
            padding: 32,
            paddingBottom: 48,
        },
        headerIcon: {
            width: 80,
            height: 80,
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        headerTitle: {
            color: colors.background,
            fontSize: 32,
            fontWeight: "bold",
            marginBottom: 8,
            textAlign: "center",
        },
        headerSubtitle: {
            color: "rgba(255,255,255,0.9)",
            fontSize: 16,
            textAlign: "center",
        },
        formSection: {
            flex: 1,
            paddingHorizontal: 20,
            marginTop: -24,
            paddingBottom: 32,
        },
        formContainer: {
            backgroundColor: colors.background,
            borderRadius: 24,
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
            padding: 20,
            marginBottom: 16,
        },
        // otpRow: {
        //     flexDirection: "row",
        //     justifyContent: "space-between",
        //     marginBottom: 24,
        // },
        // otpInput: {
        //     width: 56,
        //     height: 56,
        //     borderRadius: 12,
        //     borderWidth: 1,
        //     borderColor: colors.border,
        //     backgroundColor: colors.inputBackground,
        //     textAlign: "center",
        //     fontSize: 24,
        //     color: colors.textPrimary,
        // },
        verifyButton: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            alignItems: "center",
            marginBottom: 8,
        },
        verifyButtonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        resendText: {
            color: colors.secondary,
            fontSize: 15,
            fontWeight: "500",
        },
        successText: {
            color: colors.primary,
            fontSize: 16,
            textAlign: "center",
            marginVertical: 24,
            fontWeight: "500",
        },
        backToLoginText: {
            color: colors.secondary,
            fontSize: 15,
            fontWeight: "500",
        },
        resendBtn: {
            alignItems: "center",
            marginTop: 16,
        },
        title: {
            fontSize: 20,
            fontWeight: "bold",
            color: colors.textPrimary,
            marginBottom: 24,
        },
    });
};

export const useChangePasswordStyles = () => {
    const { colors } = useTheme();
    return StyleSheet.create({
        headerGradient: {
            backgroundColor: colors.primary,
            borderBottomLeftRadius: 48,
            borderBottomRightRadius: 48,
            padding: 32,
            paddingBottom: 48,
        },
        headerIcon: {
            width: 80,
            height: 80,
            backgroundColor: "rgba(255,255,255,0.2)",
            borderRadius: 24,
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 16,
        },
        headerTitle: {
            color: colors.background,
            fontSize: 32,
            fontWeight: "bold",
            marginBottom: 8,
            textAlign: "center",
        },
        headerSubtitle: {
            color: "rgba(255,255,255,0.9)",
            fontSize: 16,
            textAlign: "center",
        },
        formSection: {
            flex: 1,
            paddingHorizontal: 20,
            marginTop: -24,
            paddingBottom: 32,
        },
        formContainer: {
            backgroundColor: colors.background,
            borderRadius: 24,
            shadowColor: "#000",
            shadowOpacity: 0.08,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
            padding: 20,
            marginBottom: 16,
        },
        // label: {
        //     fontSize: 14,
        //     fontWeight: "500",
        //     color: colors.textSecondary,
        //     marginBottom: 8,
        // },
        // inputWrapper: {
        //     flexDirection: "row",
        //     alignItems: "center",
        //     backgroundColor: colors.inputBackground,
        //     borderRadius: 16,
        //     borderWidth: 1,
        //     borderColor: colors.border,
        //     paddingHorizontal: 12,
        //     paddingVertical: 4,
        //     position: "relative",
        //     marginBottom: 16,
        // },
        inputIcon: {
            marginRight: 8,
            color: colors.textPrimary,
        },
        // input: {
        //     flex: 1,
        //     paddingVertical: 12,
        //     fontSize: 16,
        //     color: colors.textPrimary,
        // },
        // eyeButton: {
        //     position: "absolute",
        //     right: 12,
        //     top: "50%",
        //     marginTop: -10,
        //     padding: 4,
        // },
        resetButton: {
            backgroundColor: colors.primary,
            borderRadius: 16,
            paddingVertical: 16,
            alignItems: "center",
            marginTop: 16,
        },
        resetButtonText: {
            color: colors.background,
            fontWeight: "600",
            fontSize: 16,
        },
        successText: {
            color: colors.primary,
            fontSize: 16,
            textAlign: "center",
            marginVertical: 24,
            fontWeight: "500",
        },
        backToLoginText: {
            color: colors.secondary,
            fontSize: 15,
            fontWeight: "500",
        },
        title: {
            fontSize: 20,
            fontWeight: "bold",
            color: colors.textPrimary,
            marginBottom: 24,
        },
    });
};
